
[versions]
activity = "1.3.1"
appCompat = "1.3.1"
arrow = "0.13.2"
browser = "1.3.0"
core = "1.6.0"
coroutines = "1.5.2"
dagger = "2.38.1"
datetime = "0.2.1"
either = "0.1.0-alpha.3"
gson = "2.8.8"
javierscKamp = "0.2.1"
jsoup = "1.14.2"
koin = "3.1.2"
koinCompose = "3.1.2"
kotest = "4.6.2"
kotlinInject = "0.3.6"
ksp = "1.5.30-1.0.0"
ktfmt = "0.28"
ktor = "1.6.3"
mokoki = "0.1.0-alpha.5"
moshi = "1.12.0"
okHttp = "4.9.1"
okio = "3.0.0-alpha.10"
popkorn = "2.1.1"
retrofit = "2.9.0"
retrofitKotlinConverter = "0.8.0"
runBlocking = "0.1.0-alpha.4"
semanticVersioning = "0.1.0-alpha.4"
serialization = "1.2.2"
turbine = "0.6.1"

[libraries]
activity-activityKtx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
appcompat-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }
browser-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
core-coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
cash-turbine-turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
popkorn-popkornCompiler = { group = "cc.popkorn", name = "popkorn-compiler", version.ref = "popkorn" }
popkorn-popkorn = { group = "cc.popkorn", name = "popkorn", version.ref = "popkorn" }
facebook-ktfmt = { group = "com.facebook", name = "ktfmt", version.ref = "ktfmt" }
google-codeGson-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
google-dagger-hiltAndroid = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
google-dagger-hiltCompiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger" }
google-dagger-hiltCore = { group = "com.google.dagger", name = "hilt-core", version.ref = "dagger" }
google-devtoolsKsp-symbolProcessingApi = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
jakewharton-retrofit-retrofit2KotlinxSerializationConverter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinConverter" }
javiersc-either-eitherCore = { group = "com.javiersc.either", name = "either-core", version.ref = "either" }
javiersc-either-networkCore = { group = "com.javiersc.either", name = "network-core", version.ref = "either" }
javiersc-either-networkLogger = { group = "com.javiersc.either", name = "network-logger", version.ref = "either" }
javiersc-either-networkResource = { group = "com.javiersc.either", name = "network-resource", version.ref = "either" }
javiersc-either-resourceCore = { group = "com.javiersc.either", name = "resource-core", version.ref = "either" }
javiersc-kamp-scanner = { group = "com.javiersc.kamp", name = "scanner", version.ref = "javierscKamp" }
javiersc-mokoki-mokokiCore = { group = "com.javiersc.mokoki", name = "mokoki-core", version.ref = "mokoki" }
javiersc-mokoki-mokokiSerialization = { group = "com.javiersc.mokoki", name = "mokoki-serialization", version.ref = "mokoki" }
javiersc-runBlocking-runBlockingCore = { group = "com.javiersc.run-blocking", name = "run-blocking-core", version.ref = "runBlocking" }
javiersc-runBlocking-suspendTest = { group = "com.javiersc.run-blocking", name = "suspend-test", version.ref = "runBlocking" }
javiersc-semanticVersioning-semanticVersioningCore = { group = "com.javiersc.semantic-versioning", name = "semantic-versioning-core", version.ref = "semanticVersioning" }
squareup-moshi-moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
squareup-okhttp3-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okHttp" }
squareup-okhttp3-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp" }
squareup-okio-okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
squareup-retrofit2-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
arrow-kt-arrowCore = { group = "io.arrow-kt", name = "arrow-core", version.ref = "arrow" }
arrow-kt-arrowMeta = { group = "io.arrow-kt", name = "arrow-meta", version.ref = "arrow" }
arrow-kt-arrowOptics = { group = "io.arrow-kt", name = "arrow-optics", version.ref = "arrow" }
insert-koin-koinAndroid = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
insert-koin-koinAndroidxCompose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koinCompose" }
insert-koin-koinCore = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
insert-koin-koinTest = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
kotest-kotestAssertionsCore = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
ktor-ktorClientCio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-ktorClientCore = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-ktorClientMock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
ktor-ktorClientSerialization = { group = "io.ktor", name = "ktor-client-serialization", version.ref = "ktor" }
tatarka-inject-kotlinInjectCompilerKapt = { group = "me.tatarka.inject", name = "kotlin-inject-compiler-kapt", version.ref = "kotlinInject" }
tatarka-inject-kotlinInjectCompilerKsp = { group = "me.tatarka.inject", name = "kotlin-inject-compiler-ksp", version.ref = "kotlinInject" }
tatarka-inject-kotlinInjectRuntime = { group = "me.tatarka.inject", name = "kotlin-inject-runtime", version.ref = "kotlinInject" }
jetbrains-kotlin-kotlinReflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect" }
jetbrains-kotlin-kotlinTest = { group = "org.jetbrains.kotlin", name = "kotlin-test" }
jetbrains-kotlin-kotlinTestCommon = { group = "org.jetbrains.kotlin", name = "kotlin-test-common" }
jetbrains-kotlin-kotlinTestJunit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit" }
jetbrains-kotlinx-kotlinxCoroutinesCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
jetbrains-kotlinx-kotlinxCoroutinesTest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
jetbrains-kotlinx-kotlinxDatetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }
jetbrains-kotlinx-kotlinxSerializationCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serialization" }
jetbrains-kotlinx-kotlinxSerializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
jsoup-jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }